service: devops-candidate-test-2

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  

functions:
  hello:
    handler: src/handler.app
