service: devops-candidate-test-2

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-west-1
  

functions:
  hello:
<<<<<<< HEAD
    handler: tests/test.randomNum
=======
    handler: tests/truncate.truncate
>>>>>>> a72fa305a93a7b13254f2b2b6eb213fe34027bbc

